import {
    Download,
    FileCheck
} from "lucide-react"



export default function DownloadSubmission(){


function download(){


window.open(

"http://127.0.0.1:8000/api/download-submission",

"_blank"

)


}




return (

<div

style={{

background:
"linear-gradient(135deg,#312e81,#0891b2)",

padding:30,

borderRadius:20,

marginTop:30,

color:"white"

}}

>


<FileCheck size={40}/>


<h2>

🏆 Challenge Submission Ready

</h2>


<p>

Download final ranked CSV generated by ContextRank AI.

</p>



<ul>


<li>
100,000 candidates ranked
</li>


<li>
Semantic AI scoring
</li>


<li>
Explainable reasoning included
</li>


<li>
Validation passed ✅
</li>


</ul>





<button

onClick={download}

style={{

padding:"14px 30px",

border:"none",

borderRadius:14,

fontWeight:900,

cursor:"pointer"

}}

>


<Download size={18}/>

 Download Submission CSV


</button>



</div>

)

}